polls/common/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

app_name = 'common'

urlpatterns = [
    # path('signup/', views.signup, name='signup'),
    # path('login/', auth_views.LoginView.as_view(template_name="common/login.html"), name='login'),
    # path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('signin/', views.signin, name='signin'),
    path('logout/', views.signout, name='signout'),
    path('mypage/', views.mypage, name='mypage'),
    path('<str:username>/', views.mypage_delete, name='mypage_delete'),
    path('mypage_update/<str:username>/', views.mypage_update, name='mypage_update'),
]

polls/config/urls.py
from django.contrib import admin
from django.urls import path, include

from poll import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('poll/', include('poll.urls')),
    path('', views.index2),
    path('community/', include('community.urls')),
    path('notice/', include('notice.urls')),
    path('information/', include('information.urls')),
    path('news/', include('news.urls')),
    path('interior/', include('interior.urls')),
    path('review/', include('review.urls')),
    path('introduction/', include('introduction.urls')),
    path('calculate/', include('calculate.urls')),
    path('map/', include('map.urls')),
    path('koreaCalendar/', include('koreaCalendar.urls')),
    path('common/', include('common.urls')),
    path('accounts/', include('allauth.urls')),
]

polls/map/urls.py
from django.urls import path

from . import views

app_name = 'map'

urlpatterns = [
    path("", views.search, name="search"),   # 지도
    path("map_search/", views.map_search, name="map_search"),
    path("map_convert/", views.map_convert, name="map_convert"),
]

polls/review/urls.py
from django.urls import path

from . import views

app_name = 'review'

urlpatterns = [
    path('review_main/', views.review_list_main, name='review_main'), # 거래 후기 메인
    path('review_recommend/', views.review_recommend, name='review_recommend'),  # 거래후기 게시판 추천수 보기
    path('review_jan/', views.review_list_jan, name='review_jan'), # 거래후기전세
    path('review_jan_recommend/', views.review_list_jan_recommend, name='review_jan_recommend'), # 거래후기전세
    path('review_mama/', views.review_list_mama, name='review_mama'), # 거래후기매매
    path('review_mama_recommend/', views.review_list_mama_recommend, name='review_mama_recommend'), # 거래후기매매
    path('review_subscription/', views.review_list_subscription, name='review_subscription'), # 거래후기청약
    path('review_subscription_recommend/', views.review_list_subscription_recommend, name='review_subscription_recommend'), # 거래후기청약

    path('review_detail/<int:review_board_id>/', views.review_detail, name='review_detail'), # 거래후기보기

    path('review/<int:review_board_id>/', views.comment_create, name='comment_create'), # 댓글생성
    path('comment_update/<int:comment_id>',views.comment_update,name='comment_update'), # 댓글 수정
    path('comment_delete/<int:comment_id>',views.comment_delete,name='comment_delete'), # 댓글 삭제

    path('review_delete/<int:comment_id>',views.review_delete, name='review_delete'), # 게시판 삭제
    path('review_update/<int:review_board_id>',views.review_update, name='review_update'), # 게시판 수정

    path('review_wirte/', views.review_write, name='write'),


]

polls/review/models.py
from django.contrib.auth.models import User
from django.db import models

class Review_Board(models.Model):
    r_title = models.CharField(max_length=100)
    r_content = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    r_regdate = models.DateTimeField()
    r_modifydate = models.DateTimeField(null=True, blank=True)
    r_type = models.CharField(max_length=10) # 리뷰 게시판 타입
    r_hit = models.IntegerField(default=0)
    r_recommend = models.IntegerField(default=0)

    def __str__(self):
        return str(self.r_title)

class Answer_Review(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)  # 글쓴이
    content = models.TextField()  # 답변내용
    create_date = models.DateTimeField()  # 등록일
    board_type = models.CharField(max_length=10)  # 게시판 타입 (예: 'free', 'review')
    board_id = models.PositiveIntegerField()  # 게시판 아이디 (Free_Board 또는 Review_Board의 pk)

    def __str__(self):
        return self.content

polls/review/forms.py
from django import forms

from .models import Review_Board, Answer_Review


class FreeForm(forms.ModelForm):
    class Meta:
        model = Review_Board
        fields = ['r_title', 'r_content', 'r_type']
        labels = {
            'r_title': '제목',
            'r_content': '내용',
            'r_type': '구분',
        }


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer_Review
        fields = ['content']
        labels = {
            'content': '내용'
        }

polls/review/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from .forms import FreeForm, AnswerForm
from .models import Review_Board, Answer_Review

def review_list_main(request):
    question_list = Review_Board.objects.order_by('-r_regdate')
    page = request.GET.get('page', '1')
    paginator = Paginator(question_list, 10)
    text = paginator.get_page(page)

    context = {'question_list': text}
    return render(request, 'review/review_list_main.html', context) # 거래후기 게시판

def review_recommend(request):
    question_list = Review_Board.objects.order_by('-r_recommend')
    page = request.GET.get('page', '1')
    paginator = Paginator(question_list, 10)
    text = paginator.get_page(page)

    context = {'question_list': text}
    return render(request, 'review/review_list_main.html', context) # 거래후기 게시판

def review_list_jan(request):
    question_list = Review_Board.objects.filter(r_type='전/월세').order_by('-r_regdate')
    page = request.GET.get('page', '1')
    paginator = Paginator(question_list, 10)
    text = paginator.get_page(page)

    context = {'question_list': text}
    return render(request, 'review/review_list_jan.html', context) #전세게시판

def review_list_jan_recommend(request):
    question_list = Review_Board.objects.filter(r_type='전/월세').order_by('-r_recommend')
    page = request.GET.get('page', '1')
    paginator = Paginator(question_list, 10)
    text = paginator.get_page(page)

    context = {'question_list': text}
    return render(request, 'review/review_list_jan.html', context)

def review_list_mama(request):
    question_list = Review_Board.objects.filter(r_type='매매').order_by('-r_regdate')
    page = request.GET.get('page', '1')
    paginator = Paginator(question_list, 10)
    text = paginator.get_page(page)

    context = {'question_list': text}
    return render(request, 'review/review_list_mama.html', context)

def review_list_mama_recommend(request):
    question_list = Review_Board.objects.filter(r_type='매매').order_by('-r_recommend')
    page = request.GET.get('page', '1')
    paginator = Paginator(question_list, 10)
    text = paginator.get_page(page)

    context = {'question_list': text}
    return render(request, 'review/review_list_mama.html', context)

def review_list_subscription(request):
    question_list = Review_Board.objects.filter(r_type='청약').order_by('-r_regdate')
    page = request.GET.get('page', '1')
    paginator = Paginator(question_list, 10)
    text = paginator.get_page(page)

    context = {'question_list': text}
    return render(request, 'review/review_list_subscription.html', context)

def review_list_subscription_recommend(request):
    question_list = Review_Board.objects.filter(r_type='청약').order_by('-r_recommend')
    page = request.GET.get('page', '1')
    paginator = Paginator(question_list, 10)
    text = paginator.get_page(page)

    context = {'question_list': text}
    return render(request, 'review/review_list_mama.html', context)


#########################      함수시작영역  ############################################


def review_detail(request, review_board_id): # 게시글 상세보기
    review_board = get_object_or_404(Review_Board, id=review_board_id)


    # 게시글 추천 테스트
    if request.method == 'POST':
        # 게시글 추천처리
        review_board.r_recommend += 1
        review_board.save()
        return redirect('review:review_detail', review_board_id=review_board_id)
    else:
        review_board.r_hit += 1
        review_board.save()

    # AnswerForm과 연관된 데이터 필터링
    answers_list = Answer_Review.objects.filter(board_id=review_board_id)

    context = {'review_board': review_board, 'answers_list':answers_list}
    return render(request, 'review/review_detail.html', context)



def review_write(request): # 게시글 작성
    if request.method == "POST":
        form = FreeForm(request.POST)

        if form.is_valid():
            free = form.save(commit=False)
            free.user = request.user
            free.r_regdate = timezone.now()
            free.save()

            return redirect('review:review_main')
    else:
        form = FreeForm()

    context = {'form': form, 'free_board': {'user': request.user, 'r_regdate': timezone.now()}}
    return render(request, 'review/review_write.html', context) # 게시판 작성

def comment_create(request, review_board_id):
    # 댓글 등록
    review_board = get_object_or_404(Review_Board, pk=review_board_id)

    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user  # 세션
            comment.create_date = timezone.now()
            comment.question = review_board
            comment.board_type = 'Review_Board'
            comment.board_id = review_board.pk
            comment.save()
            return redirect('review:review_detail',review_board_id=review_board_id)
    else:
        form=AnswerForm
    context = {'review_board' : review_board, 'form' : form}
    return render(request, 'review/review_detail.html',context)


@login_required(login_url='community:signin')
def comment_delete(request, comment_id):
    comment = get_object_or_404(Answer_Review, pk=comment_id)
    comment.delete()
    return redirect('review:review_detail', review_board_id=comment.board_id) # 댓글 삭제


@login_required(login_url='community:signin')
def comment_update(request, comment_id):
    comment = get_object_or_404(Answer_Review, pk=comment_id)
    if request.method == 'POST':
        form = AnswerForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.save()
            return redirect('review:review_detail', review_board_id=comment.board_id)

    else:
        form = AnswerForm(instance=comment)
    context = {'form': form}
    return render(request, 'review/review_comment_update.html', context) # 댓글 수정

# 게시판 삭제
@login_required(login_url='community:signin')
def review_delete(request, comment_id):
    comment = get_object_or_404(Review_Board, pk=comment_id)
    comment.delete()
    return redirect('review:review_main')

# 게시판 수정

# views.py

@login_required(login_url='community:signin')
def review_update(request, review_board_id):
    review_board = get_object_or_404(Review_Board, pk=review_board_id)

    if request.method == "POST":
        form = FreeForm(request.POST, instance=review_board)

        if form.is_valid():
            review = form.save(commit=False)
            review.r_modifydate = timezone.now()
            review.user = request.user
            review.save()

            return redirect('review:review_detail', review_board_id=review_board_id)
    else:
        form = FreeForm(instance=review_board)

    context = {'form': form, 'review_board': review_board}
    return render(request, 'review/review_update.html', context)

polls/templates/review/review_list_jan.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>전/월세 후기</title>
   <link rel="stylesheet" href="{% static 'css/review/css/css.css' %}">
</head>

<body>
{% include 'poll/sidebar.html' %}
{% include 'poll/header.html' %}
    <div class="board_wrap">

        <div class="board_list_wrap">

            <div class="category_wrap">
                <ul>
                    <li><a href="{% url 'review:review_main' %}">전체</a></li>
                    <li><a href="{% url 'review:review_jan' %}" class="active">전/월세</a></li>
                    <li><a href="{% url 'review:review_mama' %}" >매매</a></li>
                    <li><a href="{% url 'review:review_subscription' %}" >청약</a></li>
                </ul>
            </div>
            <div class="board_title_takes">
                <a href="{% url 'review:review_jan' %}">최신순</a>
                <a href="{% url 'review:review_jan_recommend' %}">추천순</a>
            </div>
            <div class="board_list">
                <div class="top">
                    <div class="num">번호</div>
                    <div class="title">제목</div>
                    <div class="writer">글쓴이</div>
                    <div class="date">작성일</div>
                    <div class="count">조회</div>
                    <div class="count">추천수</div>
                    <div class="division">구분</div>
                </div>

                {% for question in question_list %}
                <div>
                    <div class="num">{{ question.id }}</div>
                    <div class="title"><a href="{% url 'review:review_detail' question.id %}">{{ question.r_title }}</a></div>
                    <div class="writer">{{ question.user }}</div>
                    <div class="date">{{ question.r_regdate|date:"y-m-d" }}</div>
                    <div class="count">{{ question.r_hit }}</div>
                    <div class="count">{{ question.r_recommend }}</div>
                    <div class="division">{{question.r_type}}</div>
                </div>
                {% endfor %}

            </div>

            <!-- 페이지 처리 영역 -->
            <ul class="board_page">
                <!-- 이전 페이지 -->
                {% if question_list.has_previous %}
                <li class="bt first">
                    <a class="bt prev" href="?page={{ question_list.previous_page_number }}">◀</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="bt prev">◁</a>
                </li>
                {% endif %}

                <!-- 현재 페이지 -->
                {% for page_number in question_list.paginator.page_range %}
                <!-- 현재 페이지와 리스트의 페이지가 일치하면 활성화함 -->
                {% if question_list.number == page_number %}
                <li class="page-item active">
                    <a class="num">{{ page_number }}</a>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="num" href="?page={{ page_number }}">{{ page_number }}</a>
                </li>
                {% endif %}
                {% endfor %}

                <!-- 다음 페이지 -->
                {% if question_list.has_next %}
                <li class="page-item">
                    <a class="bt last" href="?page={{ question_list.next_page_number }}">▶</a>
                </li>
                {% else %}
                <!--이전 페이지가 없어도 적용됨-->
                <li class="page-item disabled">
                    <a class="bt last">▷</a>
                </li>
                {% endif %}
            </ul>
             <div class="bt_wrap">
            <!--로그인 안되면 로그인시 이용가능하게 설정 -->
            {% if user.is_authenticated %}

            <a href="{% url 'review:write' %}" class="on">등록</a>
            {% else %}
            <a href="{% url 'common:signin' %}" class="on">로그인시 이용가능</a>
            {% endif %}
            </div>
        </div>
    </div>
{% include 'poll/footer.html' %}
</body>

</html>

polls/templates/review/review_list_main.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>거래후기 게시판</title>
    <link rel="stylesheet" href="{% static 'css/review/css/css.css' %}">
</head>

<body>
{% include 'poll/sidebar.html' %}
{% include 'poll/header.html' %}
    <div class="board_wrap">
        <div class="board_title">
            <strong>거래후기 게시판</strong>
        </div>
        <div class="board_list_wrap">

            <div class="category_wrap">
                <ul>
                    <li><a href="{% url 'review:review_main' %}"  class="active">전체</a></li>
                    <li><a href="{% url 'review:review_jan' %}" >전/월세</a></li>
                    <li><a href="{% url 'review:review_mama' %}" >매매</a></li>
                    <li><a href="{% url 'review:review_subscription' %}" >청약</a></li>
                </ul>
            </div>

            <div class="board_title_takes">
                <a href="{% url 'review:review_main' %}">최신순</a>
                <a href="{% url 'review:review_recommend' %}">추천순</a>
            </div>
            <div class="board_list">
                <div class="top">
                    <div class="num">번호</div>
                    <div class="title">제목</div>
                    <div class="writer">글쓴이</div>
                    <div class="date">작성일</div>
                    <div class="count">조회</div>
                    <div class="recommend">추천수</div>
                    <div class="division">구분</div>
                </div>

                {% for question in question_list %}
                <div>
                    <div class="num">{{ question.id }}</div>
                    <div class="title"><a href="{% url 'review:review_detail' question.id %}">{{ question.r_title }}</a></div>
                    <div class="writer">{{ question.user }}</div>
                    <div class="date">{{ question.r_regdate|date:"y-m-d" }}</div>
                    <div class="count">{{ question.r_hit }}</div>
                    <div class="recommend">{{ question.r_recommend }}</div>
                    <div class="division">{{question.r_type}}</div>
                </div>
                {% endfor %}
            </div>

            <!-- 페이지 처리 영역 -->
            <ul class="board_page">
                <!-- 이전 페이지 -->
                {% if question_list.has_previous %}
                <li class="bt first">
                    <a class="bt prev" href="?page={{ question_list.previous_page_number }}">◀</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="bt prev">◁</a>
                </li>
                {% endif %}

                <!-- 현재 페이지 -->
                {% for page_number in question_list.paginator.page_range %}
                <!-- 현재 페이지와 리스트의 페이지가 일치하면 활성화함 -->
                {% if question_list.number == page_number %}
                <li class="page-item active">
                    <a class="num">{{ page_number }}</a>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="num" href="?page={{ page_number }}">{{ page_number }}</a>
                </li>
                {% endif %}
                {% endfor %}

                <!-- 다음 페이지 -->
                {% if question_list.has_next %}
                <li class="page-item">
                    <a class="bt last" href="?page={{ question_list.next_page_number }}">▶</a>
                </li>
                {% else %}
                <!--이전 페이지가 없어도 적용됨-->
                <li class="page-item disabled">
                    <a class="bt last">▷</a>
                </li>
                {% endif %}
            </ul>
              <div class="bt_wrap">
            <!--로그인 안되면 로그인시 이용가능하게 설정 -->
            {% if user.is_authenticated %}

            <a href="{% url 'review:write' %}" class="on">등록</a>
            {% else %}
            <a href="{% url 'common:signin' %}" class="on">로그인시 이용가능</a>
            {% endif %}
            </div>

        </div>
    </div>
{% include 'poll/footer.html' %}
</body>

</html>

polls/templates/review/review_list_mama.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>매매 후기</title>
    <link rel="stylesheet" href="{% static 'css/review/css/css.css' %}">
</head>

<body>
{% include 'poll/sidebar.html' %}
{% include 'poll/header.html' %}
    <div class="board_wrap">

        <div class="board_list_wrap">

            <div class="category_wrap">
                <ul>
                    <li><a href="{% url 'review:review_main' %}">전체</a></li>
                    <li><a href="{% url 'review:review_jan' %}" >전/월세</a></li>
                    <li><a href="{% url 'review:review_mama' %}" class="active">매매</a></li>
                    <li><a href="{% url 'review:review_subscription' %}" >청약</a></li>
                </ul>
            </div>
            <div class="board_title_takes">
                <a href="{% url 'review:review_mama' %}">최신순</a>
                <a href="{% url 'review:review_mama_recommend' %}">추천순</a>
            </div>
            <div class="board_list">
                <div class="top">
                    <div class="num">번호</div>
                    <div class="title">제목</div>
                    <div class="writer">글쓴이</div>
                    <div class="date">작성일</div>
                    <div class="count">조회</div>
                    <div class="count">추천수</div>
                    <div class="division">구분</div>
                </div>

                {% for question in question_list %}
                <div>
                    <div class="num">{{ question.id }}</div>
                    <div class="title"><a href="{% url 'review:review_detail' question.id %}">{{ question.r_title }}</a></div>
                    <div class="writer">{{ question.user }}</div>
                    <div class="date">{{ question.r_regdate|date:"y-m-d" }}</div>
                    <div class="count">{{ question.r_hit }}</div>
                    <div class="count">{{ question.r_recommend }}</div>
                    <div class="division">{{question.r_type}}</div>
                </div>
                {% endfor %}

            </div>

            <!-- 페이지 처리 영역 -->
            <ul class="board_page">
                <!-- 이전 페이지 -->
                {% if question_list.has_previous %}
                <li class="bt first">
                    <a class="bt prev" href="?page={{ question_list.previous_page_number }}">◀</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="bt prev">◁</a>
                </li>
                {% endif %}

                <!-- 현재 페이지 -->
                {% for page_number in question_list.paginator.page_range %}
                <!-- 현재 페이지와 리스트의 페이지가 일치하면 활성화함 -->
                {% if question_list.number == page_number %}
                <li class="page-item active">
                    <a class="num">{{ page_number }}</a>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="num" href="?page={{ page_number }}">{{ page_number }}</a>
                </li>
                {% endif %}
                {% endfor %}

                <!-- 다음 페이지 -->
                {% if question_list.has_next %}
                <li class="page-item">
                    <a class="bt last" href="?page={{ question_list.next_page_number }}">▶</a>
                </li>
                {% else %}
                <!--이전 페이지가 없어도 적용됨-->
                <li class="page-item disabled">
                    <a class="bt last">▷</a>
                </li>
                {% endif %}
            </ul>
              <div class="bt_wrap">
            <!--로그인 안되면 로그인시 이용가능하게 설정 -->
            {% if user.is_authenticated %}

            <a href="{% url 'review:write' %}" class="on">등록</a>
            {% else %}
            <a href="{% url 'common:signin' %}" class="on">로그인시 이용가능</a>
            {% endif %}
            </div>

        </div>
    </div>
{% include 'poll/footer.html' %}
</body>

</html>

polls/templates/review/review_list_subscription.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>청약 후기</title>
    <link rel="stylesheet" href="{% static 'css/review/css/css.css' %}">
</head>

<body>
{% include 'poll/sidebar.html' %}
{% include 'poll/header.html' %}
    <div class="board_wrap">

        <div class="board_list_wrap">

            <div class="category_wrap">
                <ul>
                    <li><a href="{% url 'review:review_main' %}">전체</a></li>
                    <li><a href="{% url 'review:review_jan' %}" >전/월세</a></li>
                    <li><a href="{% url 'review:review_mama' %}" >매매</a></li>
                    <li><a href="{% url 'review:review_subscription' %}" class="active">청약</a></li>
                </ul>
            </div>
            <div class="board_title_takes">
                <a href="{% url 'review:review_subscription' %}">최신순</a>
                <a href="{% url 'review:review_subscription_recommend' %}">추천순</a>
            </div>
            <div class="board_list">
                <div class="top">
                    <div class="num">번호</div>
                    <div class="title">제목</div>
                    <div class="writer">글쓴이</div>
                    <div class="date">작성일</div>
                    <div class="count">조회</div>
                    <div class="count">추천수</div>
                    <div class="division">구분</div>
                </div>

                {% for question in question_list %}
                <div>
                    <div class="num">{{ question.id }}</div>
                    <div class="title"><a href="{% url 'review:review_detail' question.id %}">{{ question.r_title }}</a></div>
                    <div class="writer">{{ question.user }}</div>
                    <div class="date">{{ question.r_regdate|date:"y-m-d" }}</div>
                    <div class="count">{{ question.r_hit }}</div>
                    <div class="count">{{ question.r_recommend }}</div>
                    <div class="division">{{question.r_type}}</div>
                </div>
                {% endfor %}

            </div>

            <!-- 페이지 처리 영역 -->
            <ul class="board_page">
                <!-- 이전 페이지 -->
                {% if question_list.has_previous %}
                <li class="bt first">
                    <a class="bt prev" href="?page={{ question_list.previous_page_number }}">◀</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="bt prev">◁</a>
                </li>
                {% endif %}

                <!-- 현재 페이지 -->
                {% for page_number in question_list.paginator.page_range %}
                <!-- 현재 페이지와 리스트의 페이지가 일치하면 활성화함 -->
                {% if question_list.number == page_number %}
                <li class="page-item active">
                    <a class="num">{{ page_number }}</a>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="num" href="?page={{ page_number }}">{{ page_number }}</a>
                </li>
                {% endif %}
                {% endfor %}

                <!-- 다음 페이지 -->
                {% if question_list.has_next %}
                <li class="page-item">
                    <a class="bt last" href="?page={{ question_list.next_page_number }}">▶</a>
                </li>
                {% else %}
                <!--이전 페이지가 없어도 적용됨-->
                <li class="page-item disabled">
                    <a class="bt last">▷</a>
                </li>
                {% endif %}
            </ul>
              <div class="bt_wrap">
            <!--로그인 안되면 로그인시 이용가능하게 설정 -->
            {% if user.is_authenticated %}

            <a href="{% url 'review:write' %}" class="on">등록</a>
            {% else %}
            <a href="{% url 'common:signin' %}" class="on">로그인시 이용가능</a>
            {% endif %}
            </div>

        </div>
    </div>
{% include 'poll/footer.html' %}
</body>

</html>

polls/templates/review/review_update.html
<!-- review_update.html -->

<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="{% static 'css/board/css.css' %}">
</head>

<body>
    {% include 'poll/sidebar.html' %}
    {% include 'poll/header.html' %}
    <!-- write 복사해서 내용만 바꿈 -->
    <div class="board_wrap">
        <div class="board_title">
            <strong>게시글수정</strong>
            <p>게시글 수정사항이 있으시면 작성해주세요.</p>
        </div>

        <div class="board_write_wrap">
            <form action="{% url 'review:review_update' review_board.id %}" method="post">
                {% csrf_token %}
                <div class="board_write">

                    <div class="title">
                        <dl>
                            <dt>제목</dt>
                            <dd><input type="text" name="r_title" value="{{ form.r_title.value }}"></dd>
                        </dl>
                    </div>
                    <div class="info">
                        <dl>
                            <dt>글쓴이</dt>
                            <dd>{{ review_board.user }}</dd>
                        </dl>
                          <dl>
                            <dt>구분</dt>
                            <dd>
                              <select name="r_type" id="r_type">
                                        <option value="전/월세">전/월세</option>
                                        <option value="매매">매매</option>
                                        <option value="청약">청약</option>
                                </select>
                            </dd>
                        </dl>
                    </div>



                    <div class="cont">
                        <textarea name="r_content">{{ form.r_content.value }}</textarea>
                    </div>
                </div>

                <div class="bt_wrap">
                    <button type="submit" class="on">수정</button>
                   <a href="{% url 'review:review_detail' review_board_id=review_board.id %}">취소</a>
                </div>
            </form>
        </div>
    </div>
   {% include 'poll/footer.html' %}
</body>

</html>