polls/config/urls.py
from django.contrib import admin
from django.urls import path, include

from poll import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('poll/', include('poll.urls')),
    path('', views.index2),
    path('community/', include('community.urls')),
    path('notice/', include('notice.urls')),
    path('information/', include('information.urls')),
    path('news/', include('news.urls')),
    path('interior/', include('interior.urls')),
    path('review/', include('review.urls')),
    path('introduction/', include('introduction.urls')),
    path('calculate/', include('calculate.urls')),
    path('map/', include('map.urls')),
    path('koreaCalendar/', include('koreaCalendar.urls')),
    path('common/', include('common.urls')),
    path('accounts/', include('allauth.urls')),
]

polls/information/urls.py
from django.urls import path
from . import views

app_name = 'information'

urlpatterns = [
    path('information/', views.information, name='information'),
    path('info_budong/', views.info_budong, name='info_budong'),
    path('info_jutak/', views.info_jutak, name='info_jutak'),
    path('info_trouble/', views.info_trouble, name='info_trouble'),
    path('info_gondong_trouble/', views.info_gondong_trouble, name='info_gondong_trouble'),
    path('info_smart_blue', views.info_smart_blue, name='info_smart_blue'),
    path('info_smart_jansa', views.info_smart_jansa, name='info_smart_jansa'),
    path('info_smart_mama', views.info_smart_mama, name='info_smart_mama'),
]

polls/map/urls.py
from django.urls import path

from . import views

app_name = 'map'

urlpatterns = [
    path("", views.search, name="search"),   # 지도
    path("map_search/", views.map_search, name="map_search"),
    path("map_convert/", views.map_convert, name="map_convert"),
]

polls/information/models.py
from django.db import models

# Create your models here.

polls/information/views.py
from django.shortcuts import render

# Create your views here.
def information(request):
    return render(request, 'information/information.html') # 알려드립니다메인

def info_budong(request):
    return render(request, 'information/category/info_budong.html')# 주택

def info_jutak(request):
    return render(request, 'information/category/info_jutak.html')# 주택

def info_trouble(request):
    return render(request, 'information/category/info_trouble.html')# 주택임대차분쟁

def info_gondong_trouble(request):
    return render(request, 'information/category/info_gondong_trouble.html') # 공동주택관리분쟁

def info_smart_blue(request):
    return render(request, 'information/smart/info_smart_blue.html') # 따라쟁이 청약

def info_smart_jansa(request):
    return render(request, 'information/smart/info_smart_jansa.html') # 따라쟁이 전세

def info_smart_mama(request):
    return render(request, 'information/smart/info_smart_mama.html') # 따라쟁이 매매

polls/templates/information/information.html
<!DOCTYPE html>
<html lang="ko">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>알려드려요</title>
    <link rel="stylesheet" href="{% static 'css/information/style.css' %}">
    <!-- CDN 방식 CDN이 뭐나면.. 안알랴줌 -->
    <script src="https://code.jquery.com/jquery-3.6.4.js"
        integrity="sha256-a9jBBRygX1Bh5lt8GZjXDzyOB+bWve9EiO7tROUtj/E=" crossorigin="anonymous"></script>
</head>

<body>
{% include 'poll/sidebar.html' %}
{% include 'poll/header.html' %}
    <section id="content">
        <h3>집집의 알려드려요!</h3>
         <ul class="tab-links">
            <li>
                <a href="{% url 'information:info_budong' %}" target="test" class="active">부동산매매</a>
            </li>
            <li>
                <a href="{% url 'information:info_jutak' %}" target="test">주택</a>
            </li>
            <li>
                <a href="{% url 'information:info_trouble' %}" target="test">주택임대차분쟁</a>
            </li>
            <li>
                <a href="{% url 'information:info_gondong_trouble' %}" target="test">공동주택관리분쟁</a>
            </li>
        </ul>
        <div class="information_box">
            <iframe src="{% url 'information:info_budong' %}" frameborder="0" width="100%" height="100%" name="test"></iframe>
        </div>
    </section>

    <div id="smart">
        <div id="smart_j">
            <h4>똑똑하게 집 구하기</h4>
            <h4 class="smart_toggle" style="cursor: pointer;">닫기</h4>
            <div class="smart_top_a">
                <a href="{% url 'information:info_smart_mama' %}" target="smart">매매</a>|
                <a href="{% url 'information:info_smart_jansa' %}" target="smart">전월세</a>|
                <a href="{% url 'information:info_smart_blue' %}" target="smart">청약</a>
            </div>
        </div>
        <div class="smart_section">
            <iframe src="{% url 'information:info_smart_mama' %}" frameborder="0" width="300px" height="300px"
                name="smart"></iframe>
        </div>
    </div>
{% include 'poll/footer.html' %}
    <script>
        // 토글테스트
        $(function(){
            // 닫기클릭하면
            $('.smart_toggle').click(function(){
                $('.smart_section').toggle().css('transition','0.3s')
                $('.smart_top_a').toggle()
                // $(this가 함수 연 주체 지금은 smart_toggle )
                // 3항 연산자로 제어
                // smart_toggle 글씨가 열기인가요? -> 닫기
                // smart_toggle 글씨가 닫기인가요? -> 열기
                // 이미지로 하는게 나을지도..
                var text = $(this).text()
                $(this).text(text === '열기' ? '닫기' : '열기');

            })
        })
    </script>

</body>

</html>