polls/common/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

app_name = 'common'

urlpatterns = [
    # path('signup/', views.signup, name='signup'),
    # path('login/', auth_views.LoginView.as_view(template_name="common/login.html"), name='login'),
    # path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('signin/', views.signin, name='signin'),
    path('logout/', views.signout, name='signout'),
    path('mypage/', views.mypage, name='mypage'),
    path('<str:username>/', views.mypage_delete, name='mypage_delete'),
    path('mypage_update/<str:username>/', views.mypage_update, name='mypage_update'),
]

polls/community/urls.py
from django.urls import path

from . import views

app_name = 'community'

urlpatterns = [
    path('board_free/', views.board_free, name='free'),  # 자유게시판
    path('board_free_recommend/', views.board_free_recommend, name='free_recommend'),  # 자유게시판 추천수 보기

    path('<int:free_board_id>/', views.board_free_detail, name='detail'),  # 게시판 상세보기

    path('board_free_update/<int:free_board_id>',views.board_free_update, name='update'), # 게시판 수정
    path('comment_update/<int:comment_id>/', views.comment_update, name='comment_update'), # 댓글 수정

    path('board_free_write/',views.board_free_write, name='write'), # 게시판 작성
    path('comment/<int:free_board_id>/', views.comment_create, name='comment_create'), # 댓글 등록

    path('board_free_delete/<int:free_board_id>/', views.board_free_delete, name='delete'),  # 게시글 삭제
    path('comment_delete/<int:comment_id>/', views.comment_delete, name='comment_delete'),  # 댓글 삭제


]

polls/config/urls.py
from django.contrib import admin
from django.urls import path, include

from poll import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('poll/', include('poll.urls')),
    path('', views.index2),
    path('community/', include('community.urls')),
    path('notice/', include('notice.urls')),
    path('information/', include('information.urls')),
    path('news/', include('news.urls')),
    path('interior/', include('interior.urls')),
    path('review/', include('review.urls')),
    path('introduction/', include('introduction.urls')),
    path('calculate/', include('calculate.urls')),
    path('map/', include('map.urls')),
    path('koreaCalendar/', include('koreaCalendar.urls')),
    path('common/', include('common.urls')),
    path('accounts/', include('allauth.urls')),
]

polls/map/urls.py
from django.urls import path

from . import views

app_name = 'map'

urlpatterns = [
    path("", views.search, name="search"),   # 지도
    path("map_search/", views.map_search, name="map_search"),
    path("map_convert/", views.map_convert, name="map_convert"),
]

polls/community/models.py
from django.contrib.auth.models import User

from django.db import models

class Free_Board(models.Model):
    b_title = models.CharField(max_length=100)
    b_content = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    b_regdate = models.DateTimeField()
    b_modifydate = models.DateTimeField(null=True, blank=True)
    b_hit = models.IntegerField(default=0)
    b_recommend = models.IntegerField(default=0)

    def __str__(self):
        return str(self.b_title)

class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)  # 글쓴이
    content = models.TextField()  # 답변내용
    create_date = models.DateTimeField()  # 등록일
    board_type = models.CharField(max_length=10)  # 게시판 타입 (예: 'free', 'review')
    board_id = models.PositiveIntegerField()  # 게시판 아이디 (Free_Board 또는 Review_Board의 pk)

    def __str__(self):
        return self.content

polls/community/forms.py
from django import forms

from .models import Answer, Free_Board

class FreeForm(forms.ModelForm):
    class Meta:
        model = Free_Board
        fields = ['b_title', 'b_content']
        labels = {
            'b_title':'제목',
            'b_content':'내용'
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content':'내용'
        }

polls/community/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import request, JsonResponse
from django.shortcuts import render, redirect,get_object_or_404
from django.utils import timezone

from .forms import FreeForm, AnswerForm
from .models import Free_Board, Answer

def board_free(request):
    question_list = Free_Board.objects.order_by('-b_regdate')
    page = request.GET.get('page', '1')
    paginator = Paginator(question_list, 10)
    text = paginator.get_page(page)

    context = {'question_list': text}
    return render(request, 'community/board_free/board_free.html', context) # 자유게시판

def board_free_recommend(request):
    question_list = Free_Board.objects.order_by('-b_recommend')
    page = request.GET.get('page', '1')
    paginator = Paginator(question_list, 10)
    text = paginator.get_page(page)

    context = {'question_list': text}
    return render(request, 'community/board_free/board_free.html', context) # 자유게시판

def board_free_detail(request, free_board_id):
    free_board = get_object_or_404(Free_Board, id=free_board_id)

    # 게시글 추천 테스트
    if request.method == 'POST':
        # 게시글 추천처리
        free_board.b_recommend += 1
        free_board.save()
        return redirect('community:detail', free_board_id=free_board_id)
    else:
        free_board.b_hit += 1
        free_board.save()

    # AnswerForm과 연관된 데이터 필터링
    answers_list = Answer.objects.filter(board_id=free_board_id)

    context = {'free_board': free_board, 'answers_list':answers_list}
    return render(request, 'community/board_free/board_free_detail.html', context) # 게시판 상세보기

def board_free_write(request):
    if request.method == "POST":
        form = FreeForm(request.POST)

        if form.is_valid():
            free = form.save(commit=False)
            free.user = request.user
            free.b_regdate = timezone.now()
            free.save()

            return redirect('community:free')
    else:
        form = FreeForm()

    context = {'form': form, 'free_board': {'user': request.user, 'b_regdate': timezone.now()}}

    return render(request, 'community/board_free/board_free_write.html', context) # 게시판 작성


def comment_create(request, free_board_id):
    # 댓글 등록
    free_board = get_object_or_404(Free_Board, pk=free_board_id)

    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user   # 세션
            comment.create_date = timezone.now()
            comment.question = free_board
            comment.board_type = 'Free_Board'
            comment.board_id = free_board_id
            comment.save()
            return redirect('community:detail', free_board_id=free_board_id)
    else:
        form = AnswerForm()

    context = {'free_board':free_board, 'form':form}
    return render(request, 'community/board_free/board_free_detail.html', context)

def board_free_update(request, free_board_id):
    free_board = get_object_or_404(Free_Board, pk=free_board_id)

    if request.method == "POST":
        form = FreeForm(request.POST, instance=free_board)

        if form.is_valid():
            free = form.save(commit=False)
            free.b_modifydate = timezone.now()
            free.user = request.user
            free.save()

            return redirect('community:detail', free_board_id=free_board_id)

    else:
        form = FreeForm(instance=free_board)

    context = {'form': form, 'free_board':free_board}
    return render(request, 'community/board_free/board_free_update.html', context) # 게시판 수정

@login_required(login_url='community:signin')
def board_free_delete(request, free_board_id):
    free_board = get_object_or_404(Free_Board, pk=free_board_id)
    free_board.delete()
    return redirect('community:free') #게시글 삭제


@login_required(login_url='community:signin')
def comment_delete(request, comment_id):
    comment = get_object_or_404(Answer, pk=comment_id)
    comment.delete()
    return redirect('community:detail', free_board_id=comment.board_id) # 댓글 삭제

@login_required(login_url='community:signin')
def comment_update(request, comment_id):
    comment = get_object_or_404(Answer, pk=comment_id)
    if request.method == 'POST':
        form = AnswerForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.save()
            return redirect('community:detail', free_board_id=comment.board_id)
    else:
        form = AnswerForm(instance=comment)
    context = {'form': form}
    return render(request, 'community/board_free/board_free_comment_update.html', context)

polls/templates/community/board_free/board_free.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>게시글 목록</title>
    <link rel="stylesheet" href="{% static 'css/board/css.css' %}">
</head>

<body>

{% include 'poll/sidebar.html' %}
{% include 'poll/header.html' %}

<div class="board_wrap">
    <div class="board_title">
        <strong>자유게시판</strong>
        <div class="board_title_takes">
            <a href="{% url 'community:free' %}">최신순</a> |
            <a href="{% url 'community:free_recommend' %}">추천순</a>
        </div>
    </div>


    <div class="board_list_wrap">
        <div class="board_list">
            <div class="top">
                <div class="num">번호</div>
                <div class="title">제목</div>
                <div class="writer">글쓴이</div>
                <div class="date">작성일</div>
                <div class="count">조회</div>
                <div class="recommend">추천수</div>

            </div>

            {% for question in question_list %}
            <div>
                <div class="num">{{ question.id }}</div>
                <div class="title">
                    <a href="{% url 'community:detail' question.id %}">{{ question.b_title }}

                    </a>
                    {% if question.answer_set.count > 0 %}
                        [{{question.num_answers }}]
                    {% endif %}
                </div>
                <div class="writer">{{ question.user }}</div>
                <div class="date">{{ question.b_regdate|date:"y-m-d"}}</div>
                <div class="count">{{ question.b_hit }}</div>
                <div class="recommend">{{ question.b_recommend }}</div>

            </div>
            {% endfor %}


        </div>

        <!-- 페이지 처리 영역 -->
        <ul class="board_page">
            <!-- 이전 페이지 -->
            {% if question_list.has_previous %}
            <li class="bt first">
                <a class="bt prev" href="?page={{ question_list.previous_page_number }}">◀</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="bt prev">◁</a>
            </li>
            {% endif %}

            <!-- 현재 페이지 -->
            {% for page_number in question_list.paginator.page_range %}
            <!-- 현재 페이지와 리스트의 페이지가 일치하면 활성화함 -->
            {% if question_list.number == page_number %}
            <li class="page-item active">
                <a class="num">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="num" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% endif %}
            {% endfor %}

            <!-- 다음 페이지 -->
            {% if question_list.has_next %}
            <li class="page-item">
                <a class="bt last" href="?page={{ question_list.next_page_number }}">▶</a>
            </li>
            {% else %}
            <!--이전 페이지가 없어도 적용됨-->
            <li class="page-item disabled">
                <a class="bt last">▷</a>
            </li>
            {% endif %}
        </ul>

       <div class="bt_wrap">
        <!--로그인 안되면 로그인시 이용가능하게 설정 -->
        {% if user.is_authenticated %}

        <a href="{% url 'community:write' %}" class="on">등록</a>
        {% else %}
        <a href="{% url 'common:signin' %}" class="on">로그인시 이용가능</a>
        {% endif %}
        </div>



    </div>
</div>
{% include 'poll/footer.html' %}
</body>

</html>

polls/templates/community/board_free/board_free_comment_update.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title></title>
    <style>
        .question-form {
            width: 80%;
            margin: 0 auto;
            padding: 20px;
            background-color: #f2f2f2;
        }

        #question-form-section {
            margin-bottom: 20px;
        }

        .question-form-title {
            font-size: 22px;
            font-weight: bold;
            margin-bottom: 10px;
        }

        .form-group {
            margin-bottom: 15px;
        }

        label {
            display: block;
            font-weight: bold;
            margin-bottom: 5px;
        }

        textarea {
            width: 100%;
            height: 150px;
            padding: 5px;
            border: 1px solid #ccc;
        }

       .submit-button {
            background-color: #000;
            color: #fff;
            padding: 10px 20px;
            border: none;
            cursor: pointer;
        }

        .submit-button:hover {
            background-color: #333;
        }

        .alert {
            background-color: #f44336;
            color: white;
            padding: 10px;
            margin-bottom: 10px;
        }
    </style>
</head>
<body>
{% include 'poll/sidebar.html' %}
{% include 'poll/header.html' %}
<div class="question-form">

    <section id="question-form-section">
        <h1 class="question-form-title">답글 수정</h1>
        <form action="" method="post" class="question-form">
            {% csrf_token %}
            <!-- 오류 메시지 -->
            {% if form.errors %}
                <div class="alert alert-danger">
                    {% for field in form %}
                        {% if field.errors %}
                            <strong>{{ field.label }}</strong>
                            {{ field.errors }}
                        {% endif %}
                    {% endfor %}
                </div>
            {% endif %}
            <!-- 오류 메시지 -->

            <div class="form-group">
                <label for="content">내용</label>
                <textarea id="content" name="content" required>{{ form.content.value|default_if_none:'' }}</textarea>
            </div>
            <button type="submit" class="submit-button">저장하기</button>
        </form>
    </section>
</div>
{% include 'poll/footer.html' %}
</body>
</html>

polls/templates/community/board_free/board_free_detail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>게시글 상세보기</title>
    <link rel="stylesheet" href="{% static 'css/board/css.css' %}">
    <script src="https://code.jquery.com/jquery-3.7.0.js"
            integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM=" crossorigin="anonymous"></script>
</head>

<body>
{% include 'poll/sidebar.html' %}
{% include 'poll/header.html' %}
<div class="board_wrap">
    <div class="board_view_wrap">
        <div class="board_view">
            <div class="title">
                {{ free_board.b_title }}
            </div>
            <div class="info">
                <dl>
                    <dt>번호</dt>
                    <dd>{{free_board.id}}</dd>
                </dl>
                <dl>
                    <dt>글쓴이</dt>
                    <dd>{{free_board.user}}</dd>
                </dl>
                {% if free_board.b_modifydate %}
                <dl>
                    <dt>작성일</dt>
                    <dd>{{ free_board.b_regdate|date:"y-m-d"}}</dd>
                </dl>
                <dl>
                    <dt>수정일</dt>
                    <dd>{{ free_board.b_modifydate|date:"y-m-d"}}</dd>
                </dl>
                {% else %}
                <dl>
                    <dt>작성일</dt>
                    <dd>{{ free_board.b_regdate|date:"y-m-d"}}</dd>
                </dl>
                {% endif %}
                <dl>
                    <dt>조회</dt>
                    <dd>{{free_board.b_hit}}</dd>
                </dl>
                <dl>
                    <dt>추천수</dt>
                    <dd id="recommendation_count">{{ free_board.b_recommend }}</dd>
                </dl>
            </div>

            <div class="cont" style="white-space: pre-wrap;">{{free_board.b_content}}</div>
            <div class="recommendation_button">
                <form action="{% url 'community:detail' free_board.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="custombutton">추천</button>
                </form>
            </div>
        </div>

    </div>
    <div style="" class="answer_wrap">
        {{ answers_list.count }}개의 답변이 있습니다
        {% for ans in answers_list %}
        <div class="comment">
            {% if ans.author == request.user %}
            <button class="custombutton delete" data-uri="{% url 'community:comment_delete' ans.id %}">삭제</button>
            <button class="custombutton update" data-uri="{% url 'community:comment_update' ans.id %}">수정</button>
            {% endif %}
            <p>작성자: {{ ans.author }}</p>
            <p>{{ ans.content }}</p>
        </div>


        {% endfor %}
    </div>

    {% if user.is_authenticated %}
    <section style="padding-top: 20px;margin-top:20px;">
        <h2>댓글 등록</h2>

        <form class="comment-form" action="{% url 'community:comment_create' free_board.id %}" method="post">
            {% csrf_token %}
            <textarea name="content" rows="10" required></textarea>
            <button type="submit" class="custom-button">저장</button>
        </form>
    </section>
    {% else %}
    <h2>로그인시 댓글 이용 가능합니다.</h2>
    {% endif %}
    {% if free_board.user == request.user %}
    <div class="bt_wrap">
        <a href="{% url 'community:free' %}" class="on">목록</a>
        <a href="{% url 'community:update' free_board.id %}">수정</a>
        <a href="{% url 'community:delete' free_board.id  %}" class="board_delete"
           data-uri="{% url 'community:delete' free_board.id %}">삭제</a>
    </div>
    {% else %}
    <div class="bt_wrap">
        <a href="{% url 'community:free' %}" class="on">목록</a>
    </div>
    {% endif %}
</div>

{% include 'poll/footer.html' %}
<script>
      $(document).ready(function(){
            $('.delete').click(function(e){  //삭제 버튼을 클릭하면
                e.preventDefault();  // 기본 동작인 링크 이동을 중지합니다.
                if(confirm('정말 수정/삭제하시겠습니까?')){
                    location.href=$(this).data('uri'); //현재 대상 객체의 주소를 이동
                }
            });
        });
</script>

</body>

</html>

polls/templates/community/board_free/board_free_update.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>게시글</title>
    <link rel="stylesheet" href="{% static 'css/board/css.css' %}">
</head>

<body>
{% include 'poll/sidebar.html' %}
{% include 'poll/header.html' %}
<!-- write 복사해서 내용만 바꿈 -->
<div class="board_wrap">
    <div class="board_title">
        <strong>게시글수정</strong>
        <p>게시글 수정사항이 있으시면 작성해주세요.</p>
    </div>

    <div class="board_write_wrap">
        <form action="{% url 'community:update' free_board.id %}" method="post">
            {% csrf_token %}
            <div class="board_write">

                <div class="title">
                    <dl>
                        <dt>제목</dt>
                        <dd><input type="text" name="b_title" value="{{ free_board.b_title }}"></dd>
                    </dl>
                </div>
                <div class="info">
                    <dl>
                        <dt>글쓴이</dt>
                        <dd>{{ free_board.user }}</dd>
                    </dl>
                </div>
                <div class="cont">
                    <textarea name="b_content">{{ free_board.b_content }}</textarea>
                </div>
            </div>

            <div class="bt_wrap">
                <button type="submit" class="on">수정</button>
                <a href="{% url 'community:detail' free_board.id %}">취소</a>
            </div>
        </form>
    </div>
</div>
{% include 'poll/footer.html' %}
</body>

</html>

polls/templates/community/board_free/board_free_write.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>게시글 작성</title>
    <link rel="stylesheet" href="{% static 'css/board/css.css' %}">

</head>

<body>
{% include 'poll/sidebar.html' %}
{% include 'poll/header.html' %}
<form method="post">
    {% csrf_token %}

    {% if form.errors %}

    {% for field in form %}
    {% if field.errors %}
    {{ field.label }}
    {{ field.errors }}
    {% endif %}
    {% endfor %}

    {% endif %}
    <div class="board_wrap">
        <div class="board_title">
            <h1>질문 등록</h1>

        </div>
        <div class="board_write_wrap">
            <div class="board_write">
                <div class="title">
                    <dl>
                        <dt>제목</dt>
                        <input type="text" name="b_title" id="b_title"
                               value="{{ form.b_title.value|default_if_none:'' }}" placeholder="제목 입력" required>
                    </dl>
                </div>
                <div class="info">
                    <dl>
                        <dt>글쓴이</dt>
                        <dd>{{free_board.user}}</dd>
                    </dl>

                    <dl>
                        <dt>작성일</dt>
                        <dd>{{ free_board.b_regdate|date:"y-m-d"}}</dd>
                    </dl>

                </div>
                <div class="cont">
                    <label for="b_content"></label>
                        <textarea name="b_content" id="b_content" rows="10" placeholder="내용입력" required>{{form.b_content.value|default_if_none:''}}</textarea>
                </div>
            </div>
            <div class="bt_wrap">

                <button type="submit" class="custom-submit-button">등록</button>
                <a href="{% url 'community:free' %}">취소</a>
            </div>
        </div>
    </div>

</form>
{% include 'poll/footer.html' %}
</body>

</html>